global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus tá»± monitor
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'goshop-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-production-815c.up.railway.app']

  - job_name: 'foodfast-delivery-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-production-62e6.up.railway.app']
