global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus tá»± monitor

  - job_name: 'goshop-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-production-815c.up.railway.app']

  - job_name: 'foodfast-backend'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-production-62e6.up.railway.app']
